### ISSUE TITLE
bug: a long long pending;

### ISSUE THREAD

**Issue by zhangshuo00** [tushoudadaima/tushoudadaima.github.io#1]
``

**Comment by zhangshuo00** [comment]
`<script src="/./main.0cf68a.js">`

**Comment by tushoudadaima** [comment]
sorry,i can not understand what you say,there is a long long pending.




我会发光i
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tushoudadaima/tushoudadaima.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 中午11:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tushoudadaima/tushoudadaima.github.io] bug: a long long pending; (Issue #1)





 
``

**Comment by tushoudadaima** [comment]
别叭叭，不改




我会发光i
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tushoudadaima/tushoudadaima.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 中午11:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [tushoudadaima/tushoudadaima.github.io] bug: a long long pending; (Issue #1)





 
<script src="/./main.0cf68a.js"&gt;

**Comment by zhangshuo00** [comment]
https://github.com/litten/hexo-theme-yilia/issues/580

https://blog.csdn.net/qq_42820594/article/details/109258424
